"""Add pgvector and note chunks

Revision ID: 8ba4e2bf6dd6
Revises: c6ea24de7afd
Create Date: 2026-05-27 11:06:59.521475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

class PGVector(sa.types.UserDefinedType):
    def __init__(self, dim: int) -> None:
        self.dim = dim

    def get_col_spec(self, **kw) -> str:
        return f"vector({self.dim})"


# revision identifiers, used by Alembic.
revision: str = '8ba4e2bf6dd6'
down_revision: Union[str, None] = 'c6ea24de7afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('note_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('embedding', PGVector(768), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_chunks_id'), 'note_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_note_chunks_note_id'), 'note_chunks', ['note_id'], unique=False)
    op.execute("CREATE INDEX IF NOT EXISTS ix_note_chunks_embedding_hnsw ON note_chunks USING hnsw (embedding vector_cosine_ops)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_note_chunks_embedding_hnsw")
    op.drop_index(op.f('ix_note_chunks_note_id'), table_name='note_chunks')
    op.drop_index(op.f('ix_note_chunks_id'), table_name='note_chunks')
    op.drop_table('note_chunks')
    op.execute("DROP EXTENSION IF EXISTS vector CASCADE")
    # ### end Alembic commands ###
